# Spring Boot Configuration
spring.application.name=pongpin
server.port=8081

# RabbitMQ Connection Properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ application topology
app.rabbitmq.exchange=pongpin.exchange
app.rabbitmq.queues.email.name=email.queue
app.rabbitmq.queues.email.routing-key=email.send
app.rabbitmq.queues.priority.high.name=email.high.queue
app.rabbitmq.queues.priority.high.routing-key=email.priority.high
app.rabbitmq.queues.priority.medium.name=email.medium.queue
app.rabbitmq.queues.priority.medium.routing-key=email.priority.medium
app.rabbitmq.queues.priority.low.name=email.low.queue
app.rabbitmq.queues.priority.low.routing-key=email.priority.low
spring.web.resources.static-locations=classpath:/pages/
