# Spring Boot Configuration
spring.application.name=pongpin
server.port=8080

# RabbitMQ Connection Properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# RabbitMQ application topology
app.rabbitmq.exchange=pongpin.exchange
app.rabbitmq.queues.email.name=email.queue
app.rabbitmq.queues.email.routing-key=email.send
